import './globals.css'
import type { Metadata } from 'next'
// import { Baloo_2 } from 'next/font/google'

// const Balboo = Baloo_2({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      {/* <body className={inter.className}>{children}</body> */}
      {/* <body suppressHydrationWarning={true}> {children}</body> */}
      <body>
        {/* <main className={`${Balboo.className}`}></main> */}
        {children} <div id="portal"></div>
      </body>
    </html>
  )
}
