name: Merge Swagger Files

on:
  push:
    paths:
      - 'backend/src/main/resources/openapi/root.yaml'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Swagger CLI
      run: npm install -g swagger-cli

    - name: Merge Swagger Files
      run: swagger-cli bundle -r -t yaml backend/src/main/resources/openapi/root.yaml -o docs/output.yaml

    - name: Commit and Push Merged Swagger
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add docs/output.yaml
        git commit -m "Merged swagger files"
        git push

